//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodAnalyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PodAnalyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property should not be assigned to itself.
        /// </summary>
        internal static string POD001Description {
            get {
                return ResourceManager.GetString("POD001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is assigned to itself.
        /// </summary>
        internal static string POD001MessageFormat {
            get {
                return ResourceManager.GetString("POD001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property should not be assigned to itself.
        /// </summary>
        internal static string POD001Title {
            get {
                return ResourceManager.GetString("POD001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getter-only properties should be assigned to.
        /// </summary>
        internal static string POD002Description {
            get {
                return ResourceManager.GetString("POD002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getter-only property &apos;{0}&apos; was never assigned to.
        /// </summary>
        internal static string POD002MessageFormat {
            get {
                return ResourceManager.GetString("POD002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getter-only properties should be assigned to.
        /// </summary>
        internal static string POD002Title {
            get {
                return ResourceManager.GetString("POD002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type can be made immutable.
        /// </summary>
        internal static string POD003Description {
            get {
                return ResourceManager.GetString("POD003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; can be made immutable.
        /// </summary>
        internal static string POD003MessageFormat {
            get {
                return ResourceManager.GetString("POD003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type can be made immutable.
        /// </summary>
        internal static string POD003Title {
            get {
                return ResourceManager.GetString("POD003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor parameters should be used.
        /// </summary>
        internal static string POD004Description {
            get {
                return ResourceManager.GetString("POD004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; was never used.
        /// </summary>
        internal static string POD004MessageFormat {
            get {
                return ResourceManager.GetString("POD004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor parameters should be used.
        /// </summary>
        internal static string POD004Title {
            get {
                return ResourceManager.GetString("POD004Title", resourceCulture);
            }
        }
    }
}
